### ISSUE TITLE
markdown.extensions.toc compatibility issue

### ISSUE THREAD

**Issue by AugustinWinther** [polarwinkel/mdtex2html#4]
First of, thank you for this derivation of the Python-Markdown module! Saved me a lot of time hehe. Just wanted to let you know about a extension compatibility issue.

The [`toc`](https://python-markdown.github.io/extensions/toc/) extension is one of the [officially supported extensions](https://python-markdown.github.io/extensions/#officially-supported-extensions) of Python-Markdown. It is used to generate a Table of Contents at any arbitrary point in the file by inserting the tag `[TOC]`. 

When using the `"toc"` extension with mdtex2html, it will only be able to generate a table of contents of the headers before the first codeblock. I assume this is due to the extension needing to see the all of the headers when converting, something that is not possible with mdtex2html as it [splits the input markdown up in chunks based on the codeblocks](https://github.com/polarwinkel/mdtex2html/blob/c4961ed965c1ba87afcd0bd4b199b1f9d4fbc5c0/mdtex2html/__init__.py#L41) :/ 

I assume this issue will affect all extensions that need to see the whole document to work properly. 

You can run the code below to verify this:

`````py
import markdown
import mdtex2html

md_text = """
**Table of Contents**

[TOC]

# Can see this
## And even this

```py
print("Hello world!")
```

# But not this
## And not this
"""

md = markdown.Markdown(extensions=["toc"])
html_markdown = md.convert(md_text)
print("\n\nWITH MARKDOWN:\n" + html_markdown)

html_mdtex2html = mdtex2html.convert(md_text, extensions=["toc"])
print("\n\nWITH MDTEX2HTML:\n" + html_mdtex2html)
`````

**Comment by polarwinkel** [comment]
Hi AugustinWinther, 
thanks for your report andd your analysis. I think you are right, the code is split up to chunks which I remember having good reasons for, though I don´t know why anymore.
So it looks a little tricky right now, I'll have time to take a deeper dive into this by the end of next month. hank's for a little patience :-)

**Comment by AugustinWinther** [comment]
> I'll have time to take a deeper dive into this by the end of next month. hank's for a little patience :-)

No worries :) I did however now manage to find [a Python-Markdown extension that does MathML conversion](https://pypi.org/project/L2M4M/) (released last month actually) which is able to do what I want, so I'll be sticking with that one :)

**Comment by polarwinkel** [comment]
I just pushed a fix for this, your verification code runs now as expected.
I'll do some more testing in my production systems and check other extensions for similar bugs before releasing a new version.

Thanks again for your detailed and clear report!
